name: basecode
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.0.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  uuid: ^4.4.0
  file_picker: ^8.0.6
  firebase_storage: ^12.1.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/apple.png
    - assets/facebook.png
    - assets/google.png
    - assets/logo.png
    - assets/illustrations/
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
